chat/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from django.conf.urls import url

from .views import ThreadView, InboxView,room,index,IndexView,ClientView,WriterView

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view()),
    path("index/",index,name='index'),
    path('writers/',WriterView.as_view(),name='writer'),
    path('support/',ClientView.as_view(),name='client'),
    url(r'^index/', IndexView.as_view(template_name="search.html"),
                   name='chat_room'),
    re_path(r"^writers/(?P<username>[\w.@+-]+)", ThreadView.as_view(),name='threads'),
    re_path(r'^(?P<room_name>[^/]+)/$',room,name='room')
]

chats/urls.py
from django.urls import path
from .views import Review,ReviewDetail,ChatBot,ChatRoom

app_name='chats'

urlpatterns = [
    # path('', ChatBot, name='chatbot'),
    # path('<str:room_name>/',ChatRoom, name='room'),
    path('chatty/home',Review,name='home'),
    path('detail/',ReviewDetail,name='detail'),
    
]

homeworkdoer/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls import url
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('payments/',include('payments.urls')),
    path('',views.IndexView,name='index'),
    path('about/',views.AboutView,name='about'),
    path('assignments/',include('assignments.urls')),
    path('authentication/',include('authentication.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('writers/',include('writers.urls',namespace='writers')),
    path('accounts/profile/',views.IndexView,name='profile')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

writers/urls.py
from django.urls import path
from . import views

app_name='writers'

urlpatterns=[
    path('',views.index,name='index'),
    path('join/',views.writersjoin,name='join'),
    path('upload_data/',views.document_form,name='upload_my_files'),
    
]

assignments/models.py
from django.db import models
from django_countries.fields import CountryField
from .choices import ASSIGNMENT_LEVELS,ASSIGNMENT_TYPES
from django.conf import settings
# Create your models here.
from payments.models import Membership


class Assignments(models.Model):
    slug=models.SlugField(null=True)
    level = models.CharField(max_length=20,choices=ASSIGNMENT_LEVELS)
    types = models.CharField(max_length=20,choices=ASSIGNMENT_TYPES)
    country = CountryField()
    description=models.CharField(verbose_name='course_description',max_length=255,blank=True)
    document=models.FileField(upload_to='documents/',null=True)
    uploaded_at=models.DateTimeField(auto_now_add=True)
    deadline=models.DateTimeField()
    is_approved=models.BooleanField(default=False)
    is_completed=models.BooleanField(default=False)
    revise=models.BooleanField(default=False)
    allowed_memberships=models.ManyToManyField(Membership)
    solution_format=models.CharField(max_length=200,null=True,blank=True)
    more_info=models.TextField('More Information Section',max_length=1200,null=True)

    def __str__(self):
        return self.description



class Writer(models.Model):
    slug=models.SlugField(null=True)
    title=models.CharField(max_length=120)
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='writers')
    assignments=models.ManyToManyField(Assignments)

    def __str__(self):
        return self.user.username


    

chat/models.py
from django.db import models

from django.conf import settings
from django.db import models
from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username): # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user, 
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False

       

class Thread(models.Model):
    first        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    third       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_third',null=True)
    updated      = models.DateTimeField(auto_now=True)
    timestamp    = models.DateTimeField(auto_now_add=True)
    
    objects      = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    thread      = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add=True)

    def last_10_messages():
            return ChatMessage.objects.order_by('-timestamp').all()[:10]

chats/models.py
from django.db import models

# Create your models here.

payments/models.py
import stripe
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save

stripe.api_key=settings.STRIPE_SECRET_KEY


MEMBERSHIP_CHOICES=(
    ('Free','FREE'),
    ('Q1','Quote_One'),
    ('Q2','Quote Two'),
    ('Q3','Qutoe Three'),
)


    
class Membership(models.Model):
    slug=models.SlugField()
    membership_type=models.CharField(max_length=54,choices=MEMBERSHIP_CHOICES,default='Free')
    price=models.IntegerField(default=12)
    payment_status=models.BooleanField(default=False)
    stripe_plan_id=models.CharField(max_length=40)

    def __str__(self):
        return self.membership_type 


class UserMembership(models.Model):
    user=models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    stripe_customer_id=models.CharField(max_length=40)
    membership=models.ForeignKey(Membership,on_delete=models.SET_NULL,null=True,default=4)

    # def __str__(self):
    #     return self.user
        

def post_save_usermembership_create(sender,instance,created,*args,**kwargs):
    if created:
        UserMembership.objects.get_or_create(user=instance)   

    user_membership, created = UserMembership.objects.get_or_create(user=instance)

    if user_membership.stripe_customer_id is None or user_membership.stripe_customer_id=='':
        new_customer_id=stripe.Customer.create(email=instance.email)
        user_membership.stripe_customer_id=new_customer_id['id']
        user_membership.save()

post_save.connect(post_save_usermembership_create,sender=settings.AUTH_USER_MODEL)




class Subscription(models.Model):
    user_membership=models.ForeignKey(UserMembership,on_delete=models.CASCADE)
    stripe_subscription_id=models.CharField(max_length=40)
    active=models.BooleanField(default=True)

    def  __str__(self):
        return self.user_membership.user.username

writers/models.py
from django.db import models

# Create your models here.
class WritersJoin(models.Model):
    first_name=models.CharField(max_length=500)
    last_name=models.CharField(max_length=200)
    country=models.CharField(max_length=3)
    phone=models.CharField(max_length=200)
    additional_phone=models.CharField(max_length=200)
    email=models.EmailField()
    password=models.CharField(max_length=200)
    confirm_password=models.CharField(max_length=200)
    first_discipline=models.CharField(max_length=200)
    second_discipline=models.CharField(max_length=200)
    third_discipline=models.CharField(max_length=200)
    fourth_discipline=models.CharField(max_length=200)
    fifth_discipline=models.CharField(max_length=200)
    academic_degree=models.CharField(max_length=200)
    time_zone=models.CharField(max_length=200)
    night_calls=models.BooleanField(default=False)

    def __str__(self):
        return self.first_name


class Document(models.Model):
    description=models.CharField(max_length=255,blank=True)
    document=models.FileField(upload_to='documents/')
    uploaded_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.description
        

chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

writers/forms.py
from django import forms

from .models import WritersJoin,Document

class JoinWritersForm(forms.ModelForm):
    class Meta:
        model=WritersJoin
        fields='__all__'


class DocumentForm(forms.ModelForm):
    class Meta:
        model=Document
        fields=('description','document')
        

chat/views.py
import stripe
import json
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.utils.safestring import mark_safe
from django.urls import reverse,reverse_lazy
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView,CreateView
from django.views.generic import TemplateView

from assignments.models import Assignments
from assignments.filters import AssignmentFilter
from authentication.models import User,Notification
from payments.models import UserMembership
from .forms import ComposeForm
from .models import Thread, ChatMessage

stripe.api_key = settings.STRIPE_SECRET_KEY # new


class IndexView(TemplateView):
    template_name = "search.html"



class ClientView(TemplateView):
    template_name = "chat/clients.html"
    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class WriterView(LoginRequiredMixin, ListView):
    template_name = "chat/writers.html"
    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)




class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'
    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = None

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username  = self.kwargs.get("username")
        obj, created    = Thread.objects.get_or_new(self.request.user, other_username)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['key'] = settings.STRIPE_PUBLISHABLE_KEY
        context['form'] = self.get_form()
        # add the dictionary during initialization
        data = Assignments.objects.all().first()
        
        user_membership=UserMembership.objects.filter(user=self.request.user).first()
        # if user_membership:
        # if user_membership is not None:
        # import pdb; pdb.set_trace()
        user_membership_type=user_membership.membership.membership_type

        assignment_allowed_memberships=data.allowed_memberships.all() 

        context["data"] = None
        # if user_membership_type is not None

        if assignment_allowed_memberships.filter(membership_type=user_membership_type).exists():
            context['data'] = data

        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

    def get_success_url(self, **kwargs):         
       return '{}'.format(reverse('chat:threads', kwargs={'username': self.kwargs.get('username')}))



def index(request):
    return render(request, 'chat/base.html', {})


@login_required
def room(request,room_name={'room_name':'support'}):
    # add the dictionary during initialization
    assignment_list = Assignments.objects.all()
    assignment_filter = AssignmentFilter(request.GET, queryset=assignment_list)
    if request.user.is_authenticated:
        notifications=Notification.objects.filter(user=request.user,viewed=False)

    return render(request,'chat/clients.html',{
        'room_name_json':mark_safe(json.dumps(room_name)),
        'username':mark_safe(json.dumps(request.user.username)),
        'filter':assignment_filter
    })

chats/views.py
from django.shortcuts import render

# Create your views here.
def Review(request):
    return render(request,'blog-home.html')


def ReviewDetail(request):
    return render(request,'blog-details.html')

def ChatBot(request):
    return render(request, 'chatbot.html')

def ChatRoom(request, room_name):
    return render(request, 'room.html', {
        'room_name': room_name
    })

writers/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView
from .forms import JoinWritersForm,DocumentForm
from .models import WritersJoin,Document

# Create your views here.
def index(request):
    return render(request,'writers_index.html')


def writersjoin(request):
    form=JoinWritersForm(request.POST or None)
    if form.is_valid():
        form.save()

    context={'form':form}

    return render(request,'writers_join.html',context)


def document_form(request):
    data=Document.objects.all()
    if request.method=='POST':
        # import pdb; pdb.set_trace()
        form=DocumentForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return render(request,'writers_upload.html',{
                'form':form,'data':data
            })
    else:
        form=DocumentForm()

    return render(request,'writers_upload.html',{
        'form':form,'data':data
    })



class documentList(ListView):
    model=Document
    template_name='writers_upload.html'

chat/templates/chat/home.html
{% extends "chat/base.html" %}

{% block content %}

<p class='lead'>Welcome Home</p>
{% endblock %}

chat/templates/chat/room.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,300' rel='stylesheet' type='text/css'>
    <script src="https://use.typekit.net/hoy3lrg.js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>
  </head>

<body>
  <div class="container">
  <div class="row">
    {% if request.user.is_superuser %}
    <div class="col-6">
      <div class="row">
        <div class="col-md-6 col-lg-6 bg-secondary text-white">
            <p>Action</p>
            <p>Order Number</p>
            <p>Order Type</p>
            <p>Amount</p>
            <p>Payment Status</p>
            <p>Academic Level</p>
            <p>Solution Format</p>
            <p>Request Type</p>
            <p>DeadLine</p>
            <p>Course Description</p>
            <p>More Information</p>
        </div>
        <div class="col-md-6 col-lg-6">
            {% for assignment in filter.qs %}
            {% if forloop.first %}
            <div class="button-group">
                <button class="btn btn-primary btn-sm"><i class="fa fa-upload">upload</i></button>
                <button class="btn btn-danger btn-sm"><i class="fa fa-close">cancel order</i></button>
                <button class="btn btn-success btn-sm"><i class="fa fa-list">order section</i></button>
            </div>
            {% for order in assignment.allowed_memberships.all %}
            <p>{{order.stripe_plan_id}}</p>
            <p>{{order.get_membership_type_display}}</p>
            <p>${{order.price}}</p>
            {% if order.payment_status %}
            <div class="alert alert-success" role="alert">
                Payment completed
            </div>
            {% else %}
            <div class="alert alert-warning" role="alert">
                Pending Quote
            </div>
            {% endif %}
            {% endfor %}
            <p>{{assignment.get_level_display}}</p>
            <p>{{assignment.solution_format}}</p>
            <p>{{assignment.get_types_display}}</p>
            <p>{{assignment.deadline}}</p>
            <p>{{assignment.course_description}}</p>
            <p>{{assignment.more_info}}</p>
            {% endif  %}
            {% endfor %}
        </div>
    </div>
    {% endif %}
    </div>
    <div class="{% if request.user.is_superuser %}col-6{% else %}col-12{% endif %}">
      <div id="frame">
        <div class="card">
          <div class="card-header bg-success">
            <nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark">
              <a class="navbar-brand" href="#">Chats</a>
              
            
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fa fa-bell">
                        <span class="badge badge-primary"></span>
                      </i>
                    </a>
                    {% if notifications.count > 0 %}
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      {% for n in notifications %}
                      <a class="dropdown-item" href="/authentication/notification/{{n.id}}/">{{n.title}}</a>
                      {% endfor %}
                    </div>
                    {% endif %}
                  </li>
                </ul>
                
              </div>
            </nav>
            
            <p>{{ username }}</p>
          </div>
          <div class="card-body">
            <ul id="chat-log">
              {% comment %} <li class="sent">
                <img src="http://emilcarlsson.se/assets/mikeross.png" alt="" />
                <p>How the hell am I supposed to get a jury to believe you when I am not even sure that I do?!</p>
              </li>
              <li class="replies">
                <img src="http://emilcarlsson.se/assets/harveyspecter.png" alt="" />
                <p>When you're backed against the wall, break the god damn thing down.</p>
              </li> {% endcomment %}
            </ul>
            <div class="message-input">
              <div class="wrap">
                <input id="chat-message-input" class="form-control" type="text" placeholder="Write your message..." />
                <button id="chat-message-submit" class="submit">
                  <i class="fa fa-paper-plane" aria-hidden="true"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
  
  </div>
<script src="{% static 'main.js' %}"></script>
<script src="{% static 'reconnecting-websocket.js' %}"></script>
<script>
    var roomName = 'support';
    var username = 'luther';

    var chatSocket = new ReconnectingWebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');

    chatSocket.onopen = function(e) {
      fetchMessages();
    }

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        if (data['command'] === 'messages') {
          for (let i=0; i<data['messages'].length; i++) {
            createMessage(data['messages'][i]);
          }
        } else if (data['command'] === 'new_message'){
          createMessage(data['message']);
        }
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.getElementById('chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'command': 'new_message',
            'message': message,
            'from': username
        }));

        messageInputDom.value = '';
    };

    function fetchMessages() {
      chatSocket.send(JSON.stringify({'command': 'fetch_messages' }));
    }

    function createMessage(data) {
      var author = data['author'];
      var msgListTag = document.createElement('li');
      var imgTag = document.createElement('img');
      var pTag = document.createElement('p');
      pTag.textContent = data.content;
      
      if (author === username) {
        msgListTag.className = 'sent';
      } else {
        msgListTag.className = 'replies';
      }
      msgListTag.appendChild(imgTag);
      msgListTag.appendChild(pTag);
      document.querySelector('#chat-log').appendChild(msgListTag);
    }

</script>
</body>

</html>

chat/templates/chat/thread.html
{% extends 'chat/base.html' %}
{% block content %}



<div class="container">
  <div class="card">
  <div class="card-header">
    <h3>Writer Assignment Management.</h3>
  </div>
  
  <div class="card-body">
    <div class="row">
      <div class="col-6">
          
          
          <div class="row">
          
            <div class="col-md-6 col-lg-6 bg-secondary text-white">
                <p>Action</p>
                <p>Order Number</p>
                <p>Order Type</p>
                <p>Amount</p>
                <p>Payment Status</p>
                <p>Academic Level</p>
                <p>Solution Format</p>
                <p>Request Type</p>
                <p>DeadLine</p>
                <p>Course Description</p>
                <p>More Information</p>
            </div>


            <div class="col-md-6 col-lg-6">
                {% for assignment in filter.qs %}
                {% if forloop.first %}
                <div class="button-group">
                    <button class="btn btn-primary btn-sm"><i class="fa fa-upload">upload</i></button>
                    <button class="btn btn-danger btn-sm"><i class="fa fa-close">cancel order</i></button>
                    <button class="btn btn-success btn-sm"><i class="fa fa-list">order section</i></button>
                </div>
                {% for order in assignment.allowed_memberships.all %}
                <p>{{order.stripe_plan_id}}</p>
                <p>{{order.get_membership_type_display}}</p>
                <p>${{order.price}}</p>
                {% if order.payment_status %}
                <div class="alert alert-success" role="alert">
                    Payment completed
                </div>
                {% else %}
                <div class="alert alert-warning" role="alert">
                    Pending Quote
                </div>
                {% endif %}
                {% endfor %}
                <p>{{assignment.get_level_display}}</p>
                <p>{{assignment.solution_format}}</p>
                <p>{{assignment.get_types_display}}</p>
                <p>{{assignment.deadline}}</p>
                <p>{{assignment.course_description}}</p>
                <p>{{assignment.more_info}}</p>
                {% endif  %}
                {% endfor %}
            </div>

          </div>


      </div>
      <div class="col-6">
        
            <h3>Chat with {% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</h3>
            <!-- Content Row -->
      
      
            <!-- Content Column -->
            <!-- Project Card Example -->
            <!-- Color System -->
      
      
            <!-- Illustrations -->
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Chat Section</h6>
              </div>
              <div class="card-body">
                <div class="text-center">
                  <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="img/undraw_posting_photo.svg" alt="">
                </div>
                {% for chat in object.chatmessage_set.all %}
                <strong class="primary-font">{{chat.user}}</strong> <small class="pull-right text-muted">
                <span class="glyphicon glyphicon-time"></span>{{chat.timestamp|timesince}}</small>
                <p>
                  {{ chat.message }} &rarr;
                </p>
                {% endfor %}
                <form id='form' method='POST'> {% csrf_token %}
                  <input type="hidden" id="myUsername" value="{{user.username}}"/>
                      {{user.username}}
                      {{form.as_p }}
                  <input type='submit' class='btn btn-primary'/>
              </form>
            </div>
      
      
      </div>


    </div>
  </div>


  </div>



      <!-- Approach -->

</div>


{% endblock %}

{% block script %}

 <script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js">
</script>
<script>
// websocket scripts
var loc=window.location
console.log(loc)
var formData=$("#form")
var msgInput=$("#id_message")
var chatHolder=$("#chat-items")
var me=$("#myUsername").val()

var wsStart='ws://'
if (loc.protocol=='https:'){
    wsStart='wss://'
}
var endpoint=wsStart+loc.host+loc.pathname;
var socket=new ReconnectingWebSocket(endpoint);

socket.onmessage=function(e){
    console.log("message",e)
    console.log(e.data)
    var chatDataMsg=JSON.parse(e.data)
    chatHolder.append("<li>"+chatDataMsg.message +"via"+chatDataMsg.username+"</li>")
}
socket.onopen=function(e){
    console.log("open",e)
    formData.submit(function(event){
        event.preventDefault();
        var msgText=msgInput.val()  
        // chatHolder.append("<li>"+msgText+"via"+me+"</li>");
        var formDataSerialized=formData.serialize()
        var finalData={
            "message":msgText
        } 
        socket.send(JSON.stringify(finalData))
        formData[0].reset()
    })
}
socket.onerror=function(e){
    console.log("error",e)
}
socket.onclose=function(e){
    console.log("close",e)
}

</script>
{% endblock %}

chat/templates/chat/writers.html
<div class="container">    
<h3>Chat with {% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</h3>
<!-- Content Row -->
<div class="row">

    <!-- Content Column -->
      <!-- Project Card Example -->
      <!-- Color System -->

    <div class="col-lg-6 mb-4">

      <!-- Illustrations -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Chat Section</h6>
        </div>
        <div class="card-body">
          <div class="text-center">
            <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="img/undraw_posting_photo.svg" alt="">
          </div>
          {% for chat in object.chatmessage_set.all %}
          <strong class="primary-font">{{chat.user}}</strong> <small class="pull-right text-muted">
          <span class="glyphicon glyphicon-time"></span>{{chat.timestamp|timesince}}</small>
          <p>
            {{ chat.message }} &rarr;
          </p>
          {% endfor %}
          <form id='form' method='POST'> {% csrf_token %}
            <input type="hidden" id="myUsername" value="{{user.username}}"/>
                {{user.username}}
                {{form.as_p }}
            <input type='submit' class='btn btn-primary'/>
        </form>

        </div>
      </div>

      <!-- Approach -->

</div>




 <script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js">
</script>
<script>
// websocket scripts
var loc=window.location
console.log(loc)
var formData=$("#form")
var msgInput=$("#id_message")
var chatHolder=$("#chat-items")
var me=$("#myUsername").val()

var wsStart='ws://'
if (loc.protocol=='https:'){
    wsStart='wss://'
}
var endpoint=wsStart+loc.host+loc.pathname;
var socket=new ReconnectingWebSocket(endpoint);

socket.onmessage=function(e){
    console.log("message",e)
    console.log(e.data)
    var chatDataMsg=JSON.parse(e.data)
    chatHolder.append("<li>"+chatDataMsg.message +"via"+chatDataMsg.username+"</li>")
}
socket.onopen=function(e){
    console.log("open",e)
    formData.submit(function(event){
        event.preventDefault();
        var msgText=msgInput.val()  
        // chatHolder.append("<li>"+msgText+"via"+me+"</li>");
        var formDataSerialized=formData.serialize()
        var finalData={
            "message":msgText
        } 
        socket.send(JSON.stringify(finalData))
        formData[0].reset()
    })
}
socket.onerror=function(e){
    console.log("error",e)
}
socket.onclose=function(e){
    console.log("close",e)
}

</script>