chat/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from django.conf.urls import url

from .views import ThreadView, InboxView,room,index,IndexView,ClientView,WriterView

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view()),
    path("index/",index,name='index'),
    path('writers/',WriterView.as_view(),name='writer'),
    path('support/',ClientView.as_view(),name='client'),
    url(r'^index/', IndexView.as_view(template_name="search.html"),
                   name='chat_room'),
    re_path(r"^writers/(?P<username>[\w.@+-]+)", ThreadView.as_view(),name='threads'),
    re_path(r'^(?P<room_name>[^/]+)/$',room,name='room')
]

chats/urls.py
from django.urls import path
from .views import Review,ReviewDetail,ChatBot,ChatRoom

app_name='chats'

urlpatterns = [
    # path('', ChatBot, name='chatbot'),
    # path('<str:room_name>/',ChatRoom, name='room'),
    path('chatty/home',Review,name='home'),
    path('detail/',ReviewDetail,name='detail'),
    
]

contacts/urls.py
from django.urls import path
from .views import ContactView

app_name="contacts"

urlpatterns = [
    path('',ContactView,name='home'),
]

homeworkdoer/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls import url
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('payments/',include('payments.urls')),
    path('',views.IndexView,name='index'),
    path('about/',views.AboutView,name='about'),
    path('assignments/',include('assignments.urls')),
    path('authentication/',include('authentication.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('writers/',include('writers.urls',namespace='writers')),
    path('accounts/profile/',views.IndexView,name='profile')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payments/urls.py
from django.urls import path,include
from .views import (
    PaymentIndexView,
    HomePageView,
    charge,
    MembershipSelectView,
    PaymentView,
    updateTransactions
)

app_name='payments'

urlpatterns = [
    path('', MembershipSelectView.as_view(), name='select'),
    path('payment_script/', PaymentView, name='payment'),
    path('charge/', charge, name='charge'), # new
    path('update-transactions/<subscription_id>/',updateTransactions,name='update-transactions'),
    # path('accounts/',include('django.contrib.auth.urls')),
    # path('accounts/signup/',SignupView.as_view,name='signup'),
    # path('accounts/signup/client/',ClientSignupView.as_view(),name='client_signup'),
    # path('accounts/signup/writer/',WriterSignupView.as_view(),name='writer_signup'),
    # path('accounts/signup/support/',SupportSignupView.as_view(),name='support_signup')
    # path('home/',PaymentIndexView,name='index')
    
]

assignments/models.py
from django.db import models
from django_countries.fields import CountryField
from .choices import ASSIGNMENT_LEVELS,ASSIGNMENT_TYPES
from django.conf import settings
# Create your models here.
from payments.models import Membership


class Assignments(models.Model):
    slug=models.SlugField(null=True)
    level = models.CharField(max_length=20,choices=ASSIGNMENT_LEVELS)
    types = models.CharField(max_length=20,choices=ASSIGNMENT_TYPES)
    country = CountryField()
    description=models.CharField(verbose_name='course_description',max_length=255,blank=True)
    document=models.FileField(upload_to='documents/',null=True)
    uploaded_at=models.DateTimeField(auto_now_add=True)
    deadline=models.DateTimeField()
    is_approved=models.BooleanField(default=False)
    is_completed=models.BooleanField(default=False)
    revise=models.BooleanField(default=False)
    allowed_memberships=models.ManyToManyField(Membership)
    solution_format=models.CharField(max_length=200,null=True,blank=True)
    more_info=models.TextField('More Information Section',max_length=1200,null=True)

    def __str__(self):
        return self.description



class Writer(models.Model):
    slug=models.SlugField(null=True)
    title=models.CharField(max_length=120)
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='writers')
    assignments=models.ManyToManyField(Assignments)

    def __str__(self):
        return self.user.username


    

chat/models.py
from django.db import models

from django.conf import settings
from django.db import models
from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username): # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                        first=user, 
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False

       

class Thread(models.Model):
    first        = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    third       = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_third',null=True)
    updated      = models.DateTimeField(auto_now=True)
    timestamp    = models.DateTimeField(auto_now_add=True)
    
    objects      = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    thread      = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add=True)

    def last_10_messages():
            return ChatMessage.objects.order_by('-timestamp').all()[:10]

chats/models.py
from django.db import models

# Create your models here.

contacts/models.py
from django.db import models

# Create your models here.

payments/models.py
import stripe
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save

stripe.api_key=settings.STRIPE_SECRET_KEY


MEMBERSHIP_CHOICES=(
    ('Free','FREE'),
    ('Q1','Quote_One'),
    ('Q2','Quote Two'),
    ('Q3','Qutoe Three'),
)


    
class Membership(models.Model):
    slug=models.SlugField()
    membership_type=models.CharField(max_length=54,choices=MEMBERSHIP_CHOICES,default='Free')
    price=models.IntegerField(default=12)
    payment_status=models.BooleanField(default=False)
    stripe_plan_id=models.CharField(max_length=40)

    def __str__(self):
        return self.membership_type 


class UserMembership(models.Model):
    user=models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    stripe_customer_id=models.CharField(max_length=40)
    membership=models.ForeignKey(Membership,on_delete=models.SET_NULL,null=True,default=4)

    # def __str__(self):
    #     return self.user
        

def post_save_usermembership_create(sender,instance,created,*args,**kwargs):
    if created:
        UserMembership.objects.get_or_create(user=instance)   

    user_membership, created = UserMembership.objects.get_or_create(user=instance)

    if user_membership.stripe_customer_id is None or user_membership.stripe_customer_id=='':
        new_customer_id=stripe.Customer.create(email=instance.email)
        user_membership.stripe_customer_id=new_customer_id['id']
        user_membership.save()

post_save.connect(post_save_usermembership_create,sender=settings.AUTH_USER_MODEL)




class Subscription(models.Model):
    user_membership=models.ForeignKey(UserMembership,on_delete=models.CASCADE)
    stripe_subscription_id=models.CharField(max_length=40)
    active=models.BooleanField(default=True)

    def  __str__(self):
        return self.user_membership.user.username

chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

chat/views.py
import stripe
import json
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.utils.safestring import mark_safe
from django.urls import reverse,reverse_lazy
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView,CreateView
from django.views.generic import TemplateView

from assignments.models import Assignments
from assignments.filters import AssignmentFilter
from authentication.models import User,Notification
from payments.models import UserMembership
from .forms import ComposeForm
from .models import Thread, ChatMessage

stripe.api_key = settings.STRIPE_SECRET_KEY # new


class IndexView(TemplateView):
    template_name = "search.html"



class ClientView(TemplateView):
    template_name = "chat/clients.html"
    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class WriterView(LoginRequiredMixin, ListView):
    template_name = "chat/writers.html"
    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)




class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'
    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = None

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username  = self.kwargs.get("username")
        obj, created    = Thread.objects.get_or_new(self.request.user, other_username)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['key'] = settings.STRIPE_PUBLISHABLE_KEY
        context['form'] = self.get_form()
        # add the dictionary during initialization
        data = Assignments.objects.all().first()
        
        user_membership=UserMembership.objects.filter(user=self.request.user).first()
        # if user_membership:
        # if user_membership is not None:
        # import pdb; pdb.set_trace()
        user_membership_type=user_membership.membership.membership_type

        assignment_allowed_memberships=data.allowed_memberships.all() 

        context["data"] = None
        # if user_membership_type is not None

        if assignment_allowed_memberships.filter(membership_type=user_membership_type).exists():
            context['data'] = data

        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

    def get_success_url(self, **kwargs):         
       return '{}'.format(reverse('chat:threads', kwargs={'username': self.kwargs.get('username')}))



def index(request):
    return render(request, 'chat/base.html', {})


@login_required
def room(request,room_name={'room_name':'support'}):
    # add the dictionary during initialization
    assignment_list = Assignments.objects.all()
    assignment_filter = AssignmentFilter(request.GET, queryset=assignment_list)
    if request.user.is_authenticated:
        notifications=Notification.objects.filter(user=request.user,viewed=False)

    return render(request,'chat/clients.html',{
        'room_name_json':mark_safe(json.dumps(room_name)),
        'username':mark_safe(json.dumps(request.user.username)),
        'filter':assignment_filter
    })

chats/views.py
from django.shortcuts import render

# Create your views here.
def Review(request):
    return render(request,'blog-home.html')


def ReviewDetail(request):
    return render(request,'blog-details.html')

def ChatBot(request):
    return render(request, 'chatbot.html')

def ChatRoom(request, room_name):
    return render(request, 'room.html', {
        'room_name': room_name
    })

contacts/views.py
from django.shortcuts import render

# Create your views here.
def ContactView(request):
    return render(request,'contact-us.html')

templates/assignment_detail.html
{% load crispy_forms_tags %}
{% include 'messages.html' %}
{% block content %}
{% include 'links.html' %}
{% include 'header.html' %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load humanize %}

<style type="text/css">

</style>
<hr>
<div class="content my-5">
    <hr>
    <div class="container-fluid p-7 bootstrap snippet">
        <div class="row">
            <div class="col-12">
                <h3>{{request.user.first_name}}</h3></div>
                  
            
        </div>
        <div class="card">
            <div class="card-header">
                <h2> Order Processing</h2>
            </div>
            <div class="card-body">
                
                <div class="row">
                    <div class="col-sm-4 col-lg-6">
                        
                <ul class="nav nav-tabs" id="myTab">
                    <li class="active nav-item"><a href="#home" class="nav-link" data-toggle="tab">Order</a></li>
                    <li class="nav-item"><a href="#messages" class="nav-link" data-toggle="tab">Files</a></li>
                    <li class="nav-item"><a href="#settings" class="nav-link" data-toggle="tab">Sections</a></li>
                </ul>
    
                <div class="tab-content">
                    
                    <!--/tab-pane-->
                    
                    <div class="tab-pane" id="home">
                        <hr>
                        <div class="row">
                            <div class="col-md-6 col-lg-6 bg-secondary text-white">
                                <p>Action</p>
                                <p>Order Number</p>
                                <p>Order Type</p>
                                <p>Amount</p>
                                <p>Payment Status</p>
                                <p>Academic Level</p>
                                <p>Solution Format</p>
                                <p>Request Type</p>
                                <p>DeadLine</p>
                                <p>Course Description</p>
                                <p>More Information</p>
                            </div>
                            <div class="col-md-6 col-lg-6">
                                <!-- {{filter}} -->
                                {% for assignment in filter.qs %}
                                {% if forloop.first %}
                                <div class="button-group">
                                    <button class="btn btn-success btn-sm"><i class="fa fa-list">order section</i></button>
                                </div>
                                {% for order in assignment.allowed_memberships.all %}
                                <p>{{order.stripe_plan_id}}</p>
                                <p>{{order.get_membership_type_display}}</p>
                                <p>${{order.price}}</p>
                                {% if order.payment_status %}
                                <div class="alert alert-success" role="alert">
                                    Payment completed 
                                </div>
                                {% else %}
                                <div class="alert alert-warning" role="alert">
                                    Pending Quote
                                    <a class="badge badge-primary pull-right" href="{% url 'payments:select' %}">complete payment</a>
                                </div>
                                {% endif %}
                                {% endfor %}
                                {{assignment.title}}
                                <p>{{assignment.get_level_display}}</p>
                                <p>{{assignment.solution_format}}</p>
                                <p>{{assignment.get_types_display}}</p>
                                <p>{{assignment.deadline}}</p>
                                <p>{{assignment.course_description}}</p>
                                <p>{{assignment.more_info}}</p>
                                {% endif  %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <!--/tab-pane-->
                    
                    <!-- tab-pane -->
                    <div class="tab-pane active" id="messages">
                        <div class="table-responsive">
                            
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Name</th>
                                        <th>Assignment Type</th>
                                        <th>Time Uploaded</th>
                                        <th>Uploaded By</th>
                                        
                                    </tr>
                                </thead>
                                <tbody id="items">
                                    <tr>
                                        <td>{{data.pk}}</td>
                                        {% if data is not None or membership_type == 'Free' %}
                                        <td>{{data.document}}<a href="{{data.document.url}}" download><i class="fa fa-download"></i></a></td>
                                        {% elif request.user.is_staff %}
                                        <td>{{data.document}}<a href="{{data.document.url}}" download><i class="fa fa-download"></i></a></td>
                                        {% else %}
                                        <td><a href="{% url 'payments:select' %}" class="btn btn-sm btn-warning"> <i class="fa fa-money"></i> Make Payments To access</a></td>
                                        {% endif %}
                                        <td>{{ data.get_types_display }}.</td>
                                        <td>{{ data.uploaded_at|timesince}} ago.</td>
                                        <td>{{ request.user.username }}</td>
                                    </tr>
                         
                                </tbody>
                            </table>
                            <hr>
                            <div class="row">
                                <div class="col-md-4 col-md-offset-4 text-center">
                                    <ul class="pagination" id="myPager"></ul>
                                </div>
                            </div>
                        </div>
                        <!--/table-resp-->
    
                        <hr>
    
                    </div>
    
                
                </div>
                <!--/tab-pane-->
            </div>
            <hr>
            <!--/tab-content-->
            <div class="col-sm-4 col-lg-6">
                <div class="card">
                    <div class="card-header">
                        <h2>Support Conversation</h2>
                    </div>
                    <div class="card-body">
                        {% if not request.user.is_staff %}
                        {% url 'chat:index' as the_url %}
                        {% include 'chat/room.html' with link=the_url %}
                        {% endif %}
                        {% if request.user.is_staff %}
                        {% include 'chat/writers.html' %}
                        {% endif %}
                    </div>
                </div>
    
    
                
    
    
        </div>
        <!--/col-9-->
    
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">New message</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <form>
                    <div class="form-group">
                      <label for="recipient-name" class="col-form-label">Recipient:</label>
                      <input type="text" class="form-control" id="recipient-name">
                    </div>
                    <div class="form-group">
                      <label for="message-text" class="col-form-label">Message:</label>
                      <textarea class="form-control" id="message-text"></textarea>
                    </div>
                  </form>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary">Send message</button>
                </div>
              </div>
            </div>
          </div>
         
          </div>
          
          
    </div>
</div>

<!--/row-->
  {% include 'scripts.html' %}


{% endblock %}

templates/fetch_chat.html
<div class="container">
	<div class='row alert-success'>
{% for data in data1 reversed%}


{% if data.uid == request.session.id%}
	<div class='row alert-success'>
	
		<div class="col-md-1"> </div>
  		<div class="col-md-11 text-right"><label><pre>{{data.chat}}</pre></label></div>
  </div>
	{% else %}

	<div class='row alert-success'>
    	<div class="col-md-10"><label><pre>{{data.chat}}</pre></label></div>
    	<div class="col-md-2"></div>
	</div>
	<hr>
	{% endif %}
{% endfor %}

templates/footer.html
{% load static %}
    <!-- Footer Area Starts -->
    <footer class="footer-area section-padding">
        <div class="footer-widget">
            <div class="container">
                <div class="row">
                    <div class="col-xl-2 col-lg-3">
                        <div class="single-widget-home mb-5 mb-lg-0">
                            <h3 class="mb-4">top products</h3>
                            <ul>
                                <li class="mb-2"><a href="#">managed website</a></li>
                                <li class="mb-2"><a href="#">managed reputation</a></li>
                                <li class="mb-2"><a href="#">power tools</a></li>
                                <li><a href="#">marketing service</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-5 offset-xl-1 col-lg-6">
                        <div class="single-widget-home mb-5 mb-lg-0">
                            <h3 class="mb-4">newsletter</h3>
                            <p class="mb-4">You can trust us. we only send promo offers, not a single.</p>  
                            <form action="#">
                                <input type="email" placeholder="Your email here" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your email here'" required>
                                <button type="submit" class="template-btn">subscribe now</button>
                            </form>
                        </div>
                    </div>
                    <div class="col-xl-3 offset-xl-1 col-lg-3">
                        <div class="single-widge-home">
                            <h3 class="mb-4">instagram feed</h3>
                            <div class="feed">
                                <img src="{% static 'images/feed1.jpg' %}" alt="feed">
                                <img src="{% static 'images/feed2.jpg' %}" alt="feed">
                                <img src="{% static 'images/feed3.jpg' %}" alt="feed">
                                <img src="{% static 'images/feed4.jpg' %}" alt="feed">
                                <img src="{% static 'images/feed5.jpg' %}" alt="feed">
                                <img src="{% static 'images/feed6.jpg' %}" alt="feed">
                                <img src="{% static 'images/feed7.jpg' %}" alt="feed">
                                <img src="{% static 'images/feed8.jpg' %}" alt="feed">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-6">
                        <span><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</span>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="social-icons">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-behance"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

templates/login.html
<!DOCTYPE html>
<html>
<style>

form {
    border: 3px solid #f1f1f1;
}

input[type=text], input[type=password]{
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
    font-size: 18px;
}

label{
	font-size: 20px;
}

button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
    font-size: 20px;
}

button:hover {
    opacity: 0.8;
}


.container {
    padding: 16px;
}

.label {
    color: white;
    padding: 8px;
    font-family: Arial;
    background-color: #f44336;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;
    }
    .cancelbtn {
       width: 100%;
    }
}
</style>
<body>
{% include 'navigation.html' %}


{% if username %}

<div class="alert alert-danger">

<center><strong><h3>Incorect matching of Username and Password!</h3></strong></center>
</div>
{% endif %}

<form action="{% url 'after_login' %}" method='post'>
 {% csrf_token %}
  <div class="container">
    <h2>User Login</h2>
    <label><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="username" required>

    <label><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required>
        
       <button type="submit">Login</button>
   
  </div>
</form>

</body>
</html>

templates/messages.html
{% if messages %}

<style type="text/css">
    div.messages{
        
    }
    ul.messages{
        list-style-type: none;
    }
</style>

<div class="alert alert-warning alert-dismissible fade show">
    <ul>
        {% for message in messages %}
        <li {% if message.tags %} class="{{message.tags}}" {% endif %}>
            {% if "html_safe" in message.tags %}
                {{message|safe}}
            {% else %}
                {{message}}
            {% endif %}
        </li>
        {% endfor %}
    </ul>
</div>

{% endif %}

templates/test_user.html
<html>
<head>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" ></script>
	<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script type="text/javascript">

function check_login(element) {
    $("#login_ok").hide();
    $("#login_not").hide();
    login = $(element).val();
    if (login == "") {
        return;
    }
    $.ajax({
        url : $(element).attr("data-url"),
        data : {
            "csrfmiddlewaretoken" : $(element).siblings("input[name='csrfmiddlewaretoken']" ).val(),
            "login":login
        },
        method: "POST",
        dataType : "json",
        success : function (returned_data) {            
            if (returned_data.is_success) {
                $("#login_ok").show();
            } else {
                $("#login_not").show();
            }
        }
    });
}
</script>
</head>
<body>
<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>


<label for="login" class="col-md-2 control-label">Login</label>
<div class="col-md-4">
    <input type="text" class="form-control input-sm" name="login" id="login" placeholder="Login or Username" required="True" onkeyup="check_login(this);return false;" data-url="{% url 'check_login' %}"/>
    {% csrf_token %}
</div>
<div class="col-md-6 col-sm-6" style="color:red;display:none;margin-top: 4px;"  id="login_not">
    <span class="glyphicon glyphicon-remove"></span> Username already taken.
</div>
<div class="col-md-6 col-sm-6" style="color: green;display: none;margin-top: 4px;" id="login_ok">
    <span class="glyphicon glyphicon-ok"></span> Username available.
</div>
</body>
</html>