authentication/urls.py
from django.urls import path
from .views import (
    UserLoginCreateView, 
    UserRegistrationCreateView,
    logout_view,
    ClientRegistrationCreateView,
    WriterRegistrationCreateView,
    show_notification,
    delete_notification,
    profile_view
)

app_name = 'authentication'

urlpatterns = [
    path('login', UserLoginCreateView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', UserRegistrationCreateView.as_view(), name='sign_up'),
    path('signup_client/', ClientRegistrationCreateView.as_view(), name='cient_sign_up'),
    path('signup_writer/', WriterRegistrationCreateView.as_view(), name='writer_sign_up'),
    path('notification/<int:notification_id>/',show_notification,name='show_notifications'),
    path('notification/delete/<int:notification_id>/',delete_notification,name='delete_notification'),
    path('profile/',profile_view,name='profile'),

]

chat/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from django.conf.urls import url

from .views import ThreadView, InboxView,room,index,IndexView,ClientView,WriterView

app_name = 'chat'
urlpatterns = [
    path("", InboxView.as_view()),
    path("index/",index,name='index'),
    path('writers/',WriterView.as_view(),name='writer'),
    path('support/',ClientView.as_view(),name='client'),
    url(r'^index/', IndexView.as_view(template_name="search.html"),
                   name='chat_room'),
    re_path(r"^writers/(?P<username>[\w.@+-]+)", ThreadView.as_view(),name='threads'),
    re_path(r'^(?P<room_name>[^/]+)/$',room,name='room')
]

homeworkdoer/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls import url
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('payments/',include('payments.urls')),
    path('',views.IndexView,name='index'),
    path('about/',views.AboutView,name='about'),
    path('assignments/',include('assignments.urls')),
    path('authentication/',include('authentication.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('writers/',include('writers.urls',namespace='writers')),
    path('accounts/profile/',views.IndexView,name='profile')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/authenticate/login.html
{% load static %} {% block content %} {% load crispy_forms_tags %}
<!DOCTYPE html>
<html class="h-100" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>
     Assignment - Homework Doer
    </title>
    <!-- Favicon icon -->
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="../../assets/images/favicon.png"
    />
    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous"> -->
    <link href="{% static 'css/styleset.css' %}" rel="stylesheet" />
  </head>

  <body class="h-100">
    <style>
      body {
        background: -webkit-gradient(
          linear,
          left top,
          left bottom,
          from(rgba(0, 0, 0, 0.9)),
          to(transparent)
        );
        background: linear-gradient(rgba(0, 0, 0, 0.9), transparent);
      }
    </style>
    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
      <div class="loader">
        <svg class="circular" viewBox="25 25 50 50">
          <circle
            class="path"
            cx="50"
            cy="50"
            r="20"
            fill="none"
            stroke-width="3"
            stroke-miterlimit="10"
          />
        </svg>
      </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->

    <div class="login-form-bg h-100">
      <div class="container h-100">
        <div class="row justify-content-center h-100">
          <div class="col-xl-6">
            <div class="form-input-content">
              <div class="card login-form mb-0">
                <div class="card-body pt-5">
                  <a class="text-center"> <h4>Elite Homework Master</h4></a>

                  <form class="mt-5 mb-5 login-input" method="POST">
                    {%if messages%}
                    <div class="alert alert-danger">
                      {% for message in messages %} {% if forloop.first %}
                      {{message}} {% endif %} {% endfor %}
                    </div>
                    {%endif%} {% csrf_token %} {% crispy form %}
                  </form>
                  <div class="row">
                    <div class="col col-md-6">
                      <p class="mt-5 login-form__footer">
                        Dont have account?
                        <a
                          href="{% url 'authentication:sign_up' %}"
                          class="text-primary"
                          >Sign Up</a
                        >
                        now
                      </p>
                    </div>
                    <div class="col col-md-6">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!--**********************************
        Scripts
    ***********************************-->
    <script src="{% static 'js/common.min.js' %}"></script>
    <script src="{% static 'js/custom.min.js' %}"></script>
    <script src="{% static 'js/settings.js' %}"></script>
    <script src="{% static 'js/gleek.js' %}"></script>
    <script src="{% static 'js/styleSwitcher.js' %}"></script>
  </body>
</html>

{% endblock %}

templates/authenticate/register.html
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Elite Homework Master</title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="../../assets/images/favicon.png">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="{% static 'css/styleset.css' %}" rel="stylesheet">

</head>

<body class="h-100">
    <style>
        body {
          background: -webkit-gradient(
            linear,
            left top,
            left bottom,
            from(rgba(0, 0, 0, 0.9)),
            to(transparent)
          );
          background: linear-gradient(rgba(0, 0, 0, 0.9), transparent);
        }
      </style>
    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->





    <div class="login-form-bg h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100">
                <div class="col-xl-6">
                    <div class="form-input-content">
                        <div class="card login-form mb-0">
                            <div class="card-body pt-5">

                                    <a class="text-center" > <h4>Elite Homework Doer</h4></a>

                                <form class="mt-5 mb-5 login-input" method="POST">
                                    {% csrf_token %}
                                    {{form|crispy}}
                                    <button class="btn login-form__btn submit w-100">Sign UP</button>
                                </form>
                                    <p class="mt-5 login-form__footer">Have account <a href="{% url 'authentication:login' %}" class="text-primary">Sign In </a> now</p>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <!--**********************************
        Scripts
    ***********************************-->
    <script src="{% static 'js/common.min.js' %}"></script>
    <script src="{% static 'js/custom.min.js' %}"></script>
    <script src="{% static 'js/settings.js' %}"></script>
    <script src="{% static 'js/gleek.js' %}"></script>
    <script src="{% static 'js/styleSwitcher.js' %}"></script>
</body>
</html>





{% endblock %}